version: '3.8'
services:
  web:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install --no-cache-dir boto3 python-dotenv && python upload_data_s3_bucket.py"
